# start app witch docker-compose up

version: '2'
services:
  # yvent:
    # image: "yvent_v2"
    # build: .
    # ports:
     # - "127.0.0.1:9001:8000"
    # volumes:
      # - .:/app
    # env_file: .env
    # working_dir: /app
    # command: bash -c 'php artisan migrate && php artisan serve --host 0.0.0.0'
    # extra_hosts:
     # - "localhost:192.168.56.1"
  web:
    image: nginx:latest
    ports:
      - "9002:80"
    volumes:
      # - ./public:/public
      - .:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: php:7.2-fpm
    volumes:
      # - ./public:/public
      - .:/app

