# start app witch docker-compose up

version: '3'
services:
  yvent:
    image: "yvent_v2"
    build: .
    ports:
      - "8009:8181"
    volumes:
      - .:/app
    env_file: .env
    working_dir: /app
    command: bash -c 'php artisan migrate && php artisan serve --host 0.0.0.0'
    extra_hosts:
     - "localhost:192.168.56.1"
